version: '3.9'

services:
  web:
    build: . # Docker ищет Dockerfile в текущей директории
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db  # Важно: используем имя сервиса вместо localhost

  db:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config.celery worker --pool=solo -l INFO
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    command: celery -A config.celery beat -l INFO
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  static_volume:
