version: '3.9'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    env_file:
      - .env.docker
    environment:
      - DATABASE_HOST=db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:16.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.docker
    restart: always  # Добавил restart
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: always  # Добавил restart
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build: .
    command: celery -A config worker --pool=solo -l INFO
    volumes:
      - .:/code
    env_file:
      - .env.docker
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: always  # Добавил restart

  celery_beat:
    build: .
    command: celery -A config beat -l INFO
    volumes:
      - .:/code
    env_file:
      - .env.docker
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: always  # Добавил restart

volumes:
  postgres_data:
  static_volume:
  redis_data: